### ISSUE TITLE
Can't stop Elasticsearch

### ISSUE THREAD

**Issue by Albo-nite** [allegro/embedded-elasticsearch#31] opened 2017-10-13 15:11 UTC
Hi.
First, nice work with Embedded elasticsearch. It's really usefull.

I found a bug since 2.4.1
When i want to stop my cluster, it's stuck in class ElasticServer.java L.182
`if (ownerThread != null) {
            ownerThread.join();
        }`

My test wait for ES to stop but the thread won't die. 

I can see in my task manager that two java threads wait each other.

In version 2.4.0 its works because windows kills all thread.

Thx for your help.

**Comment by gaczm** [comment] 2017-10-20 21:01
Hi
Sorry for late response, I'm attending conference right now. If you have this bug since 2.4.1, then it is probably caused by #24. Could you attach full log from execution and make a stacktrace when it hangs? Please also tell me if this happens from time to time, or always. I don't have windows, so I'm unable to test it by myself

**Comment by AJBrindley** [comment] 2017-10-24 17:05
Hi
I have the same problem on Windows.  It happens all the time.  There is no stacktrace, it just hangs in the ownerThread.join();

I did a little digging and it turns out you'll never get an interrupt from destroy() or waitFor(), so the ownerThread will not terminate which in turn will not allow the process to shutdown.

Your bug on windows is here (ElasticServer.java : 174):
ownerThread.join();.

If you get an RC code of 1, just interrupt the ownerThread and exit as the native Windows call is asynchronous, so it returns immediately, waiting for the thread to die, will never happen and the processes will never die.

**Comment by gaczm** [comment] 2017-10-24 19:45
> There is no stacktrace, it just hangs in the ownerThread.join()

You can always generate it with thread dump...

It seems that problem is with `destroy()` on windows, not with join. Process wasn't terminated, so owner thread cannot join. I would dig into that deeper, but I don't even have a possibility to test that on windows. So, I can simply revert #24 or someone with windows can solve that and make PR

**Comment by AJBrindley** [comment] 2017-10-25 09:55
The windows destroy() implementation is as per native windows - asynch and no callback.  As a result the ownerThread will never get an interrupt and will persist, keeping the process alive.

The best fix given the native windows behaviour would be (ElasticServer: 187):
private void stopElasticGracefully() throws IOException {
    if (SystemUtils.IS_OS_WINDOWS) {
        stopWindows();
    } else {
        elastic.destroy();
    }
}

private void stopWindows() throws IOException {
    Runtime.getRuntime().exec("taskkill /f /pid " + pid);
}

I'll fork the repo, test and submit a pull request.

**Comment by arenard** [comment] 2017-11-28 18:40
Hi,

I currently have the same problem as Elasticsearch never stops correctly under Windows.

@AJBrindley did you have a chance to partially revert #24 as you suggested in order to restore former Windows behavior ?

**Comment by wkit23** [comment] 2017-12-06 02:51
I'm also having the same problem in Windows where Elasticsearch never stops. 
At the moment, I just revert back to version 2.4.0 before the pull request.

**Comment by AndrewPonyk** [comment] 2017-12-28 13:51
@pbobruk , although issue is fixed now, the artifact with fix is not present in central maven repo.
The latest version is 2.4.2 (with old code)

**Comment by Vapsel** [comment] 2018-01-08 13:28
Up vote. I'm also waiting for this fix.

**Comment by sydorchuk-yukon** [comment] 2018-01-09 19:18
Up vote. I'm also waiting for this fix.

**Comment by bsylla** [comment] 2018-01-10 22:32
Eagerly waiting for this fix too.

**Comment by sydorchuk-yukon** [comment] 2018-01-11 09:34
I see that not only 1, but even 5 releases have appeared, The question now is when they will reach Maven Central

**Comment by gaczm** [comment] 2018-01-11 10:28
Hi all, sorry for late response. I've just released 2.4.3 version with this fix. @sydorchuk-yukon all does additional releases was created by mistake, I've already deleted them.

**Closed by gaczm** 2018-01-11 10:28 UTC
